[package]
name = "tradervue-conv"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = { version = "0.32.0", features = ["chrono"] }
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
csv = "1.4.0"
